### ISSUE TITLE
Ensure Message Order

### ISSUE THREAD

**Issue by LineMetrics** [marcelog/safe_bunny#2]
We have tested safe_bunny for a few weeks now, and so far we are pleased what it does, to ensure messages gets delivered. However, there a scenarios, where message-order gets mixed up. We understand, that this is due to the concurrency implied and mostly this is not a problem at all. But unfortunatly there are channels with which we must garantee message order.
So the question is: Do you see a possibility to ensure message order, or do you know of another solution, with which one can ensure message order and provides local queueing like safe_bunny does.
Thanks in advance

**Comment by marcelog** [comment]
Hello @LineMetrics,

First of all: I always like to keep an open mind about new features, and will be happy to discuss them. Now that I have said that, I can say that for now, I don't see a support for order of delivery in safe_bunny. Here's why.

The idea behind safe_bunny is to get rid of any messages as soon as possible, and only queue them when something very bad happens (like a connectivity issue).

My guess is that supporting order in the delivery might create a bottleneck in the delivery itself (safe_bunny would have to block -and queue!- other operations for that particular routing key, until all the previous messages are sent successfuly).

This would also imply to forfeit the advantage of concurrency in erlang (not to mention that having tasks "queued" in different backends like mysql and redis would require us to have some sort of mechanism to recognice which task comes first and from which backend, and then honor that).

Also, how could safe_bunny be sure about the order? Let's say that your own code tries to send message #10 before #3. This will happen eventually, and safe_bunny would have to be smart enough as to be aware of it and worse, do something about it.

So on one hand, I somehow try to design things so the order and retry of operations are not important. This would be best, since everything works in a very simple way, no complex machinery is needed.

On the other hand, the order of tasks can be managed by the receiver instead of the sender. If you have one (and only one) way to get an incremental order (a very naive way would be to use `incrby` operation in a redis db, or perhaps a way to get timestamps in microseconds -this would need to be a monotonic source, of course-) you can "stamp" that into your messages and then take the order into account on the receiver side.

If you are (let's say) reporting metrics that you want to show on a nice chart, you can save every message you get into your db, and then plot them in order by this field. You could query your DB sorting by this field in particular. Eventually, all the metrics will be displayed in the order that they were took from the source (instead of the order in which they were sent or received).

Another way would be to use something like [Kafka](http://kafka.apache.org/). Moving away from something like RabbitMQ. I've never actually used it yet, but I think you can consume the messages in the same order that they arrived to kafka.

Makes sense?

**Comment by LineMetrics** [comment]
Hello Marcelo, 
thank you for your eleborate answer, it totally makes sense and for the most part matches our considerations.
We might go with an ordering process on the consumer side of RabbitMQ.

alex

**Comment by marcelog** [comment]
Great! I will close this one now, but please feel free to come back and report your solution, and how that worked for you. 

Cheers!
